# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

     ## deploy 步骤  
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        ## REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        ## REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
        ## 秘钥
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
        ## 这个参数是必须的
        ARGS: "-rltgoDzv0 --delete"
        SOURCE: "dist/"
        REMOTE_HOST: "47.103.196.224"
        REMOTE_USER: "root"
        TARGET: "/usr/share/nginx/html"
